Add acquisition and analysis scripts
lnls-dig/fofb pull request #3
Opened 2024-06-26 20:58 UTC by juliacscarvalho

sysid/python_lib: SysId acquisition and analysis notebooks were added. There is also a script for  for Power Spectral Density and RMS Beam Size plots (fofb_exp_plots).

2024-06-28 17:30 UTC, juliacscarvalho commented
@ericonr @anacso17

2024-06-28 20:33 UTC, anacso17 commented on sysid/python_lib/FOFB-analysis.ipynb
> +    "        lvlsx, lvlsy = acq.get_levels_bpms_from_svd(ampmax = acq.params.svd_levels_ampmax*factor, lvl = -val*factor)\n",
Should we use here the new prbs data (beam order)?

2024-08-30 21:00 UTC, guilhermerc requested changes
Please consider the changes on `sysid/python_lib/FOFB-acquisition.ipynb` as we discussed.

2024-09-10 12:22 UTC, guilhermerc approved these changes

2025-07-03 18:49 UTC, merged